// Generate lib/geo/zcta-data.ts from the U.S. Census ZCTA gazetteer.
//
// The gazetteer is a tab-separated national file with a header row:
//   GEOID  ALAND  AWATER  ALAND_SQMI  AWATER_SQMI  INTPTLAT  INTPTLONG
// (GEOID is the 5-digit ZCTA; INTPTLAT/INTPTLONG are the centroid.)
//
// Download once from census.gov (network-enabled environment required —
// the build/CI sandbox blocks outbound fetches), unzip, then run:
//
//   node scripts/build-zcta.mjs path/to/2023_Gaz_zcta_national.txt
//
// This OVERWRITES lib/geo/zcta-data.ts with the full ~33k-row table.
// Commit the result. Source:
//   https://www.census.gov/geo/maps-data/data/gazetteer.html

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "../lib/geo/zcta-data.ts");

const input = process.argv[2];
if (!input) {
  console.error("usage: node scripts/build-zcta.mjs <gazetteer.txt>");
  process.exit(1);
}

const raw = readFileSync(input, "utf8");
const lines = raw.split(/\r?\n/).filter(Boolean);
const header = lines.shift()?.split("\t").map((h) => h.trim());
if (!header) {
  console.error("empty file");
  process.exit(1);
}

const iZip = header.indexOf("GEOID");
const iLat = header.indexOf("INTPTLAT");
const iLng = header.indexOf("INTPTLONG");
if (iZip < 0 || iLat < 0 || iLng < 0) {
  console.error(`unexpected columns: ${header.join(", ")}`);
  process.exit(1);
}

const rows = [];
for (const line of lines) {
  const cols = line.split("\t");
  const zip = cols[iZip]?.trim();
  const lat = Number(cols[iLat]);
  const lng = Number(cols[iLng]);
  if (!/^\d{5}$/.test(zip ?? "") || Number.isNaN(lat) || Number.isNaN(lng)) {
    continue;
  }
  // 4 decimals ≈ 11 m — far finer than centroid accuracy, keeps the file small.
  rows.push(`  "${zip}": [${lat.toFixed(4)}, ${lng.toFixed(4)}],`);
}
rows.sort();

const body = `// ZIP Code Tabulation Area (ZCTA) centroids: \`zip → [lat, lng]\`.
//
// GENERATED by scripts/build-zcta.mjs from the U.S. Census ZCTA gazetteer.
// Do not edit by hand — re-run the generator to refresh. See
// docs/geo-search-plan.md for context.

export type Centroid = readonly [lat: number, lng: number];

export const ZCTA_CENTROIDS: Readonly<Record<string, Centroid>> = {
${rows.join("\n")}
};
`;

writeFileSync(OUT, body);
console.log(`wrote ${rows.length} centroids to ${OUT}`);
